### ISSUE TITLE
Bringing up a question

### ISSUE THREAD

**Issue by Xavierxhq** [trojai/trojai#2]
Great thanks to the owners!

I am just wondering **which deep-learning-framework is the backbone of this package**? say tf or pytorch? I have read the docs and failed to find an answer.

Your kindly reply will be appreciated, thx!

A coder.

**Comment by Xavierxhq** [comment]
I just recall that I have not read the papers in enough detail, and then I found the answer which is PyTorch.
I may say you could consider to statement this message in your website for greater convenience.

Hope that I did not make any inconvenience to you.

A coder.

**Comment by cash** [comment]
@Xavierxhq, thanks for the feedback on our documentation.
